import AppBar from "@mui/material/AppBar";
import Container from "@mui/material/Container";
import Typography from "@mui/material/Typography";
import IconButton from "@mui/material/IconButton";
import Box from "@mui/material/Box";
import Divider from "@mui/material/Divider";
import Grid from "@mui/material/Grid";
import Stack from "@mui/material/Stack";
import React from "react";
import { createTheme, ThemeProvider } from "@mui/material/styles";

import Facebook from "@mui/icons-material/Facebook";
import Instagram from "@mui/icons-material/Instagram";
import Twitter from "@mui/icons-material/Twitter";
import YouTube from "@mui/icons-material/YouTube";

import Search from "@mui/icons-material/Search";
import ShoppingCart from "@mui/icons-material/ShoppingCart";
import Image from "next/image";
import Head from "next/head";
import { useRef } from "react";
import { useState } from "react";
import { Badge, Popover } from "@mui/material";
import { makeStyles } from "@mui/styles";
import Link from "next/link";
import Sidebar from "./Sidebar";
import { useContext } from "react";
import { ShopContext } from "./Utility";

import Cookies from "js-cookie";

function Layout(props) {
  const useStyles = makeStyles((theme) => ({
    popover: {
      pointerEvents: "none",
    },
    popoverContent: {
      pointerEvents: "auto",
    },
  }));
  const [menPopOver, setmenPopOver] = useState(false);
  const menPopoverRef = useRef(null);

  const [womenPopOver, setwomenPopOver] = useState(false);
  const womenPopoverRef = useRef(null);

  const [accPopOver, setaccPopOver] = useState(false);
  const accPopoverRef = useRef(null);

  const { openSidebar, checkout } = useContext(ShopContext);

  const theme = createTheme({
    palette: {
      mode: "light",
    },
    typography: {
      allVariants: {
        fontFamily: '"Metropolis", sans-serif',
      },
    },
  });
  const classes = useStyles();

  return (
    <ThemeProvider theme={theme}>
      <Head>
        <title>{props.title}</title>
        {props.description && (
          <meta name="description" content="Generated by create next app" />
        )}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppBar
        position="sticky"
        sx={{
          backgroundColor: "#fff",
          color: "#000",
          boxShadow: "none",
        }}
      >
        <Container fixed>
          <Box display="flex" alignItems="center">
            <Stack spacing={3} direction="row">
              <Box>
                <Link href="/men" passHref>
                  <a>
                    <Typography
                      ref={menPopoverRef}
                      aria-owns="men-over-popover"
                      aria-haspopup="true"
                      onMouseEnter={() => {
                        setmenPopOver(true);
                      }}
                      onMouseLeave={() => {
                        setmenPopOver(false);
                      }}
                    >
                      Men&apos;s
                    </Typography>
                  </a>
                </Link>
                <Popover
                  id="men-over-popover"
                  open={menPopOver}
                  className={classes.popover}
                  classes={{
                    paper: classes.popoverContent,
                  }}
                  anchorEl={menPopoverRef.current}
                  anchorOrigin={{
                    vertical: "bottom",
                    horizontal: "left",
                  }}
                  transformOrigin={{
                    vertical: "top",
                    horizontal: "left",
                  }}
                  PaperProps={{
                    onMouseEnter: () => {
                      setmenPopOver(true);
                    },
                    onMouseLeave: () => {
                      setmenPopOver(false);
                    },
                  }}
                >
                  <Box px={3} py={2}>
                    <Link href="/" passHref>
                      <a>
                        <Typography mb={1} variant="body1">
                          Short Sleeve
                        </Typography>
                      </a>
                    </Link>
                    <Link href="/" passHref>
                      <a>
                        <Typography variant="body1">Long Sleeve</Typography>
                      </a>
                    </Link>
                  </Box>
                </Popover>
              </Box>
              <Box>
                <Link href="/women" passHref>
                  <a>
                    <Typography
                      ref={womenPopoverRef}
                      aria-owns="women-over-popover"
                      aria-haspopup="true"
                      onMouseEnter={() => {
                        setwomenPopOver(true);
                      }}
                      onMouseLeave={() => {
                        setwomenPopOver(false);
                      }}
                    >
                      Women&apos;s
                    </Typography>
                  </a>
                </Link>
                <Popover
                  id="women-over-popover"
                  open={womenPopOver}
                  className={classes.popover}
                  classes={{
                    paper: classes.popoverContent,
                  }}
                  anchorEl={womenPopoverRef.current}
                  anchorOrigin={{
                    vertical: "bottom",
                    horizontal: "left",
                  }}
                  transformOrigin={{
                    vertical: "top",
                    horizontal: "left",
                  }}
                  PaperProps={{
                    onMouseEnter: () => {
                      setwomenPopOver(true);
                    },
                    onMouseLeave: () => {
                      setwomenPopOver(false);
                    },
                  }}
                >
                  <Box px={3} py={2}>
                    <Link href="/" passHref>
                      <a>
                        <Typography mb={1} variant="body1">
                          Short Sleeve
                        </Typography>
                      </a>
                    </Link>
                    <Link href="/" passHref>
                      <a>
                        <Typography variant="body1">Long Sleeve</Typography>
                      </a>
                    </Link>
                  </Box>
                </Popover>
              </Box>
              <Box>
                <Link href="/accessories" passHref>
                  <a>
                    <Typography
                      ref={accPopoverRef}
                      aria-owns="accessories-over-popover"
                      aria-haspopup="true"
                      onMouseEnter={() => {
                        setaccPopOver(true);
                      }}
                      onMouseLeave={() => {
                        setaccPopOver(false);
                      }}
                    >
                      Accessories
                    </Typography>
                  </a>
                </Link>
                <Popover
                  id="accessories-over-popover"
                  open={accPopOver}
                  className={classes.popover}
                  classes={{
                    paper: classes.popoverContent,
                  }}
                  anchorEl={accPopoverRef.current}
                  anchorOrigin={{
                    vertical: "bottom",
                    horizontal: "left",
                  }}
                  transformOrigin={{
                    vertical: "top",
                    horizontal: "left",
                  }}
                  PaperProps={{
                    onMouseEnter: () => {
                      setaccPopOver(true);
                    },
                    onMouseLeave: () => {
                      setaccPopOver(false);
                    },
                  }}
                >
                  <Box px={3} py={2}>
                    <Link href="/" passHref>
                      <a>
                        <Typography variant="body1">Hats</Typography>
                      </a>
                    </Link>
                  </Box>
                </Popover>
              </Box>
            </Stack>
            <Box
              sx={{
                flexGrow: 1,
              }}
            ></Box>
            <Box sx={{ width: "150px", height: "80px", position: "relative" }}>
              <Link href="/" passHref>
                <a>
                  <Image
                    alt="Weedoo Logo"
                    objectFit="contain"
                    layout="fill"
                    src="/images/weedoologo-head.png"
                  ></Image>
                </a>
              </Link>
            </Box>
            <Box
              sx={{
                flexGrow: 1.35,
              }}
            ></Box>
            <Box display="flex">
              <IconButton
                sx={{
                  color: "#000",
                  mr: 2,
                }}
              >
                <Search />
              </IconButton>
              <IconButton
                sx={{
                  color: "#000",
                }}
                onClick={() => {
                  openSidebar();
                }}
              >
                <Badge
                  badgeContent={
                    checkout.lineItems
                      ? checkout.lineItems.length
                      : Cookies.get("cartLength")
                  }
                  color="primary"
                >
                  <ShoppingCart />
                </Badge>
              </IconButton>
            </Box>
          </Box>
        </Container>
        <Divider />
      </AppBar>
      <Sidebar />
      <Container
        fixed
        sx={{
          my: 5,
        }}
      >
        {props.children}
      </Container>
      <footer>
        <Divider />
        <Box
          mb={9}
          mt={5}
          sx={{
            position: "relative",
            overflow: "hidden",
            "&::after": {
              content: "''",
              position: "absolute",
              width: "50%",
              height: "100%",
              background: "url(/images/weedoologo.svg)",
              backgroundRepeat: "no-repeat",
              right: "-60px",
              bottom: "-30px",
              opacity: 0.03,
              zIndex: "-1",
            },
          }}
        >
          <Container maxWidth="lg">
            <Grid container>
              <Grid item md={3.5}>
                <Box
                  mb={3}
                  sx={{ width: "150px", height: "60px", position: "relative" }}
                >
                  <Image
                    alt="Weedoo Logo"
                    objectFit="contain"
                    objectPosition="top"
                    layout="fill"
                    src="/images/weedoologo.svg"
                  ></Image>
                </Box>
                <Typography variant="body1" mb={3} fontStyle="italic">
                  WEEDOO GREENBOAT INC. <br /> 8020 Belvedere Rd Ste #1 <br />{" "}
                  West Palm Beach, FL. 33411 USA
                </Typography>
                <Stack spacing={1} mb={2}>
                  <Typography variant="body1">+1561-204-5765</Typography>
                  <Typography variant="body1">844-933 3662</Typography>
                  <Typography variant="body1">sales@weedooboats.com</Typography>
                </Stack>
                <Stack
                  direction="row"
                  spacing={2}
                  sx={{
                    ml: "-4px",
                  }}
                >
                  <IconButton
                    sx={{
                      color: "#fff",
                      backgroundColor: "#000",
                      p: "4px",
                    }}
                  >
                    <YouTube
                      sx={{
                        fontSize: "24px",
                      }}
                    />
                  </IconButton>
                  <IconButton
                    sx={{
                      color: "#fff",
                      backgroundColor: "#000",
                      p: "4px",
                    }}
                  >
                    <Instagram
                      sx={{
                        fontSize: "24px",
                      }}
                    />
                  </IconButton>
                  <IconButton
                    sx={{
                      color: "#fff",
                      backgroundColor: "#000",
                      p: "4px",
                    }}
                  >
                    <Facebook
                      sx={{
                        fontSize: "24px",
                      }}
                    />
                  </IconButton>
                  <IconButton
                    sx={{
                      color: "#fff",
                      backgroundColor: "#000",
                      p: "4px",
                    }}
                  >
                    <Twitter
                      sx={{
                        fontSize: "24px",
                      }}
                    />
                  </IconButton>
                </Stack>
              </Grid>
              <Grid item md={3}>
                <Box mb={3} sx={{ height: "60px" }}>
                  <Typography
                    variant="h6"
                    sx={{
                      letterSpacing: "2px",
                      fontWeight: "bold",
                    }}
                  >
                    SUPPORT
                  </Typography>
                </Box>
                <Stack spacing={1} mb={2}>
                  <Typography variant="body1">Customer Support</Typography>
                  <Typography variant="body1">Shipping Policy</Typography>
                  <Typography variant="body1">Privacy Policy</Typography>
                  <Typography variant="body1">Terms or Service</Typography>
                  <Typography variant="body1">
                    Return & Exchange Policy
                  </Typography>
                </Stack>
              </Grid>
              <Grid item md={2.5}>
                <Box mb={3} sx={{ height: "60px" }}>
                  <Typography
                    variant="h6"
                    sx={{
                      letterSpacing: "2px",
                      fontWeight: "bold",
                    }}
                  >
                    MAIN MENU
                  </Typography>
                </Box>
                <Stack spacing={1} mb={2}>
                  <Typography variant="body1">Shop</Typography>
                  <Typography variant="body1">Inventory</Typography>
                  <Typography variant="body1">Contact Us</Typography>
                </Stack>
              </Grid>

              <Grid item md={3}>
                <Box mb={3} sx={{ height: "60px" }}>
                  <Typography
                    variant="h6"
                    sx={{
                      letterSpacing: "2px",
                      fontWeight: "bold",
                    }}
                  >
                    SIGN UP AND SAVE
                  </Typography>
                </Box>
                <Stack spacing={1} mb={2}>
                  <Typography variant="body1">
                    Subscribe to get special orders, free giveaways, and
                    once-in-a-lifetime deals.
                  </Typography>
                </Stack>
              </Grid>
            </Grid>
          </Container>
        </Box>
      </footer>
    </ThemeProvider>
  );
}

export default Layout;
