import AppBar from "@mui/material/AppBar";
import Container from "@mui/material/Container";
import Typography from "@mui/material/Typography";
import IconButton from "@mui/material/IconButton";
import Box from "@mui/material/Box";
import Divider from "@mui/material/Divider";
import Stack from "@mui/material/Stack";
import Badge from "@mui/material/Badge";
import Input from "@mui/material/Input";
import { createTheme, ThemeProvider } from "@mui/material/styles";

import Search from "@mui/icons-material/Search";
import ShoppingCart from "@mui/icons-material/ShoppingCart";
import Menu from "@mui/icons-material/Menu";
import Image from "next/image";
import Head from "next/head";
import Link from "next/link";
import { useRef, useContext, useState } from "react";
import { ShopContext } from "./Utility";

import dynamic from "next/dynamic";
import Router from "next/router";
import { DropdownContext } from "./DropdownUtility";
const Dropdown = dynamic(() => import("./Dropdown"));
const SidebarMenu = dynamic(() => import("./SidebarMenu"));
const Sidebar = dynamic(() => import("./Sidebar"));
const Footer = dynamic(() => import("./Footer"));

function Layout(props) {
  const [menPopOver, setmenPopOver] = useState(false);
  const menPopoverRef = useRef(null);

  const [womenPopOver, setwomenPopOver] = useState(false);
  const womenPopoverRef = useRef(null);

  const [accPopOver, setaccPopOver] = useState(false);
  const accPopoverRef = useRef(null);

  const { openSidebar, checkout, openMenuSidebar, searchBar, openSearch } =
    useContext(ShopContext);
  const { menPopover, womenPopover, accPopover, OpenPopover } =
    useContext(DropdownContext);

  const theme = createTheme({
    palette: {
      mode: "light",
    },
    typography: {
      allVariants: {
        fontFamily: '"Metropolis", sans-serif',
      },
      h3: {
        fontSize: "2.4rem",

        "@media (min-width:600px)": {
          fontSize: "3rem",
        },
      },
      h4: {
        fontSize: "1.6rem",

        "@media (min-width:600px)": {
          fontSize: "2.125rem",
        },
      },
      h6: {
        fontSize: "1rem",

        "@media (min-width:600px)": {
          fontSize: "1.25rem",
        },
      },
      body1: {
        fontSize: ".85rem",

        "@media (min-width:600px)": {
          fontSize: "1rem",
        },
      },
    },
  });

  return (
    <ThemeProvider theme={theme}>
      <Head>
        <title>{props.title}</title>
        {props.description && (
          <meta name="description" content="Generated by create next app" />
        )}
        <link rel="icon" href="/images/favicon.ico" />
      </Head>
      <AppBar
        position="sticky"
        sx={{
          backgroundColor: "#fff",
          color: "#000",
          boxShadow: "none",
        }}
      >
        <Container fixed>
          <Box
            sx={{
              display: "flex",
              alignItems: "center",
              py: { xs: 2, md: 0 },
            }}
          >
            <Box
              sx={{
                display: { xs: "block", md: "none" },
              }}
            >
              <IconButton onClick={openMenuSidebar}>
                <Menu
                  sx={{
                    color: "#000",
                  }}
                />
              </IconButton>
            </Box>
            <Stack
              spacing={3}
              direction="row"
              sx={{
                alignItems: "center",
                display: { xs: "none", md: "flex" },
              }}
            >
              <Box>
                <Link href="/men" passHref>
                  <a>
                    <Typography
                      aria-owns={menPopover ? "men-over-popover" : undefined}
                      aria-haspopup="true"
                      onMouseEnter={() => {
                        OpenPopover("Men", true);
                      }}
                      onMouseLeave={() => {
                        OpenPopover("Men", false);
                      }}
                      aria-label="Men Link"
                      ref={menPopoverRef}
                    >
                      Men&apos;s
                    </Typography>
                  </a>
                </Link>
                <Dropdown
                  open={menPopover}
                  popOverRef={menPopoverRef}
                  id="men-over-popover"
                  bool="Men"
                  items={[
                    {
                      title: "Short Sleeve",
                    },
                    {
                      title: "Long Sleeve",
                    },
                  ]}
                />
              </Box>
              <Box>
                <Link href="/women" passHref>
                  <a>
                    <Typography
                      aria-label="Women Link"
                      ref={womenPopoverRef}
                      aria-owns={
                        womenPopover ? "women-over-popover" : undefined
                      }
                      aria-haspopup="true"
                      onMouseEnter={() => {
                        OpenPopover("Women", true);
                      }}
                      onMouseLeave={() => {
                        OpenPopover("Women", false);
                      }}
                    >
                      Women&apos;s
                    </Typography>
                  </a>
                </Link>
                <Dropdown
                  open={womenPopover}
                  popOverRef={womenPopoverRef}
                  id="women-over-popover"
                  bool="Women"
                  items={[
                    {
                      title: "Short Sleeve",
                    },
                    {
                      title: "Long Sleeve",
                    },
                  ]}
                />
              </Box>
              <Box>
                <Link href="/accessories" passHref>
                  <a>
                    <Typography
                      aria-label="Accessories Link"
                      ref={accPopoverRef}
                      aria-owns={
                        accPopover ? "accessories-over-popover" : undefined
                      }
                      aria-haspopup="true"
                      onMouseEnter={() => {
                        OpenPopover("Acc", true);
                      }}
                      onMouseLeave={() => {
                        OpenPopover("Acc", false);
                      }}
                    >
                      Accessories
                    </Typography>
                  </a>
                </Link>
                <Dropdown
                  open={accPopover}
                  popOverRef={accPopoverRef}
                  id="accessories-over-popover"
                  bool="Acc"
                  items={[
                    {
                      title: "Short Sleeve",
                    },
                    {
                      title: "Long Sleeve",
                    },
                  ]}
                />
              </Box>
            </Stack>
            <Box
              sx={{
                flexGrow: 1,
              }}
            ></Box>
            <Box
              sx={{
                width: "150px",
                height: "80px",
                position: "relative",
                display: { xs: "none", md: "block" },
              }}
            >
              <Link href="/" passHref>
                <a>
                  <Image
                    alt="Weedoo Logo"
                    objectFit="contain"
                    layout="fill"
                    src="/images/weedoologo-head.png"
                  ></Image>
                </a>
              </Link>
            </Box>
            <Box
              sx={{
                flexGrow: { xs: 0.75, md: 1.35 },
              }}
            ></Box>
            <Box display="flex">
              <Box position="relative">
                <Input
                  disableUnderline
                  sx={{
                    position: "absolute",
                    border: "1px solid #000",
                    borderRadius: "6px",
                    height: 40,
                    width: searchBar ? { xs: "100%", sm: 150, lg: 200 } : 0,
                    opacity: searchBar ? 1 : 0,
                    transition: "0.25s ease-out",
                    right: "60px",
                    top: "50%",
                    transform: "translateY(-50%)",
                    px: 2,
                    display: { xs: "none", sm: "block" },
                  }}
                  inputProps={{
                    sx: {
                      height: "29px",
                    },
                    "aria-label": "Search Bar",
                  }}
                  onKeyDown={(event) => {
                    if (event.key === "Enter") {
                      Router.push({
                        pathname: "/search",
                        query: { keyword: event.target.value },
                      });
                    }
                  }}
                />
                <IconButton
                  aria-label="Search Bar"
                  onClick={openSearch}
                  sx={{
                    color: "#000",
                    mr: 2,
                  }}
                >
                  <Search />
                </IconButton>
              </Box>
              <IconButton
                aria-label="Shopping Cart"
                sx={{
                  color: "#000",
                }}
                onClick={() => {
                  openSidebar();
                }}
              >
                <Badge
                  badgeContent={checkout.lineItems?.length}
                  color="primary"
                >
                  <ShoppingCart />
                </Badge>
              </IconButton>
            </Box>
          </Box>
        </Container>
        <Divider />
      </AppBar>
      <Sidebar />
      <SidebarMenu />

      <Container
        component="main"
        fixed
        sx={{
          my: 5,
        }}
      >
        {props.children}
      </Container>
      <Footer />
    </ThemeProvider>
  );
}

export default Layout;
